on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # - env:
    #     ec2_host: ${{ secrets.wm_ec2_host }}
    #     ec2_username: ${{ secrets.wm_ec2_username }}
    #     ec2_password: ${{ secrets.wm_ec2_password }}
    #   run: | 
    #     & "C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -source:contentPath="$env:github_workspace" -dest:contentPath="JanTest",computerName="$env:ec2_host",userName="$env:ec2_username",password="$env:ec2_password"
    # - uses: appleboy/scp-action@master
    #   with:
    #     host: "ec2-18-189-7-13.us-east-2.compute.amazonaws.com"
    #     username: "Administrator"
    #     password: ${{ secrets.ec2_password }}
    #     port: 22
    #     source: "README.md"
    #     target: "test"
    - uses: garygrossgarten/github-action-scp@release
      with:
        local: README.md
        remote: /inetpub/JanTest/readme
        host: ${{ secrets.ec2_host }}
        username: ${{ secrets.ec2_username }}
        password: ${{ secrets.ec2_password }}
